### ISSUE TITLE
Problems with _start

### ISSUE THREAD

**Issue by senahf** [einstein95/crunchy-xml-decoder#1]
C:\Users\me>C:\Users\me\Desktop\crunchy-xml-decoder-master\_start.bat

--------------------------
---- Start New Export ----
--------------------------

CrunchyRoll Downloader Toolkit DX v0.98

Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worth

it, and supports the animators.

----------

Please Enter CrunchyRoll Video URL
http://www.crunchyroll.com/free-iwatobi-swim-club/episode-8-the-locomotive-of-a-
twist-656405
The system cannot find the path specified.
****** Job completed successfully *****

**Comment by darkmorpher** [comment]
You have to set environment path to python directory. You can do it manually or from the python setup installer. Make sure you are using only python version **2.7.5**
