### ISSUE TITLE
Edit EXIT to be a PAUSE in start.bat

### ISSUE THREAD

**Issue by ganon11000** [einstein95/crunchy-xml-decoder#10]
It would be nice if the window didn't automatically close on completion (so you can see if it worked properly, had errors etc..) I have editied mine but I think it should be deafule

**Comment by MidgardSerpent** [comment]
open up _start.bat in a text editor and replace rem	PAUSE with PAUSE

**Comment by ganon11000** [comment]
I've already done that and set it up for me. I just am suggesting you make it a default

**Comment by einstein95** [comment]
I REM'd it out as it was a hassle when batch downloading episodes.

**Comment by ganon11000** [comment]
Surely you could add it to the end of the last episode downloaded (I get a lot of RTMP reconnects and that breaks the .mkv output)

**Comment by einstein95** [comment]
I... don't see how it breaks the mkv output, you could easily do Ctrl+C on
rtmpdump if it's not working right (forces a restart of the download). Not
sure how I could add it to "the end of the last episode downloaded" as when
batch downloading, it's doing the exact same thing for each episode.

**Comment by ganon11000** [comment]
This is the part I mean that breaks the downloaded video https://i.imgur.com/FYoMeN9.png

**Comment by ganon11000** [comment]
Also been getting a lot of these recently: https://i.imgur.com/YXMQVJj.png

**Comment by einstein95** [comment]
That means you're not running the latest version... or I need to sync my
local changes...
