### ISSUE TITLE
 [ONGOING]Unable to download any files that require hls, errors with SSL Handshake failed. (FOR A WORKAROUND SEE #84)

### ISSUE THREAD

**Issue by jaw20** [einstein95/crunchy-xml-decoder#101]
When I try to download anything that require the use of hls.py, the script seems to fail and errors out with `URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure>` 

~~Sometime I can get the script to create the .ts file its supposed to be downloading but its called"Redirecting..."~~

~~NOTE: This seems to be Series specific, seemingly only effecting Gurren Lagaan episode 13 and higher.~~

Its also worth noting that HLS with the script (at least on my end is completely broken and errors with the message above.)
~~This has been split into 2 issues, on the basis that this one deals with HLS, while the other deals with rtmp. SEE #104~~

~~Although now creating any file using the script titles it as "Redirecting..." . This is the same if I use a different computer as well.~~  (~~Not using the solution from #84~~)

**Comment by jaw20** [comment]
This seems to be persisting after a couple of days, and the only way that this can be avoided is through using RTMP only.

**Comment by jaw20** [comment]
This has to be an issue with either m3u8 or the HLS code you guys implemented. This is probably something that should be fixed ASAP. @jsonn you were the one who originally implemented hls, could you shed any light on this?

**Comment by jsonn** [comment]
This is from urllib itself. It has nothing to do with the HLS code. I certainly don't see any problems on Linux. As I said elsewhere, the most likeliest candidate is that Windows-Python simply ships an outdated SSL implememtation that can't deal with modern TLS.

**Comment by jsonn** [comment]
OK, so there was a new issue in that crunchy decided to use unencrypted segments in some cases. #98 has a fix for that as well. It won't help with the SSL handshake issue though.

**Comment by jsonn** [comment]
You can reproduce the SSL problem with the following Python code:

```
import urllib2
urllib2.urlopen("https://v.vrv.co")
```

My Windows VM certainly fails providing a working SSL handshake, Linux is perfectly fine (error 403 is expected).

**Comment by jsonn** [comment]
You might need to install a fresh Python 2.7 to get a newer OpenSSL.

**Comment by jaw20** [comment]
I have tried re-installing 2.7.5 multiple times and I think that 2.7.8 did work(in that I wasn't getting an ssl error) when I installed it. Maybe it just isn't possible to run the script on python 2.7.5 anymore.

**Comment by jaw20** [comment]
See #106

**Comment by Limitless99** [comment]
Didn't fix for me!
Now I get as #105 
TypeError: Non-hexadecimal digit found
