### ISSUE TITLE
Installing m3u8 

### ISSUE THREAD

**Issue by Limitless99** [einstein95/crunchy-xml-decoder#102]
Hello there,

I'm having trouble installing "m3u8 0.3.0".
I tried following the same steps in #95 but couldn't fix it.
Pic: 
<img width="675" alt="1" src="https://cloud.githubusercontent.com/assets/24194621/20643010/21623dc6-b3d2-11e6-84f4-553ec778e918.PNG">

And when I open "crunchy-xml-decoder" that is located in "crunchy-xml-decoder-master"
I get this message:
<img width="880" alt="2" src="https://cloud.githubusercontent.com/assets/24194621/20642980/f39f7930-b3d1-11e6-88d7-84d7d06a49aa.PNG">

**Comment by jsonn** [comment]
If you want to use m3u8 0.3.0, you need #98 and can install it with `pip install m3u8`. Otherwise, follow `pip install m3u8==0.2.10` as written in #91.

**Comment by Limitless99** [comment]
THANK YOU SO MUCH!!

**One last question**: I changed my DNS in order to see some contents that aren't available in the country i'm living in. However, the tool refuses to work. 
Is there any way to bypass that? 

I Also want to donate to you guys for developing this tool. Please provide me your donating if you have one.

**Comment by jsonn** [comment]
I don't think crunchy is using DNS-based blocks, so you will have to use a VPN.
