### ISSUE TITLE
[SOLVED] mkvmerge is unable to recognize .ts files (SEE INSIDE FOR FIX)

### ISSUE THREAD

**Issue by jaw20** [einstein95/crunchy-xml-decoder#108]
On specific files that I download(using hls), mkvmerge says that the file is not a recognized type. The specific error was ``Error: The file 'export\Re-ZERO -Starting Life in Another World- Episode 15 - The Outside of Madness.ts' has unknown type. Please have a look at the supported file types ('mkvmerge --list-types') and contact the author Moritz Bunkus <moritz@bunkus.org> if your file type is supported but not recognized properly.``

# ********TO GET AROUND THIS EDIT YOUR HLS.PY WITH THIS COMMIT https://github.com/einstein95/crunchy-xml-decoder/pull/110/commits/c07e9997cb7cb688d79a5b74e7020c16df7e3ede FROM #110 AND YOU WILL BE ABLE TO DOWNLOAD FILES********

~~(Not to say it isn't downloading, the script just removes the downloaded file because it thinks the file has been mux'ed with the sub file)~~

**Comment by jsonn** [comment]
I honestly don't know which version of mkmerge is currently in git as I don't use it. You might need to download a newer one from https://mkvtoolnix.download/downloads.html#windows and just replace the mkvmerge.exe binary.

**Comment by jaw20** [comment]
The version of mkvmerge that came with the script was 7.0.0 (Where we going). I have tried using the script, but even with 9.5.0 and 9.6.0 (the two newest version) I still get the same error.

**Comment by jaw20** [comment]
I have tried using an example .ts file that i found online, and mkvmerge can read it fine. Are you able to get .ts to go through mkvmerge on your end @jsonn ?

**Comment by jsonn** [comment]
Ah, this was a misunderstanding about the IV handling. #110 is the fix.

**Comment by Limitless99** [comment]
@jsonn 
It worked just fine now. 
THANK YOU SO MUCH!
