### ISSUE TITLE
Download Error: handshake failure 

### ISSUE THREAD

**Issue by Limitless99** [einstein95/crunchy-xml-decoder#109]
Hello,

Whenever I try to download anything, with or without enabling USA proxy. I even tried to download files I've already downloaded in order to check.

URL: 
http://www.crunchyroll.com/gintama/episode-305-shogun-assassination-arc-part-six-sworn-enemy-690601

But I get this error here:
![_01](https://cloud.githubusercontent.com/assets/24194621/20783023/4fb75430-b7d4-11e6-85b0-70b53cc8e81b.PNG)

I installed Python 2.7.9 as mentioned here #106 
However, that didn't fix it for me.

Because now I get as #105 after installing Python 2.7.9
"TypeError: Non-hexadecimal digit found"

**Comment by jsonn** [comment]
The latter should have been fixed by the merge of #98. Are you sure your sources are up-to-date?

**Comment by Limitless99** [comment]
Yes, I re-downloaded everything from [here](https://github.com/einstein95/crunchy-xml-decoder) today
I have tried "Python 2.7.9 + m3u8 0.2.10" .. Not m3u8 0.3.0

**Comment by jaw20** [comment]
Try doing m3u8 0.3.0

**Comment by jaw20** [comment]
Could you run "pip freeze" in a command prompt, and post a screen shot of the output?

**Comment by Limitless99** [comment]
@jaw20 
Here you go:
![_2](https://cloud.githubusercontent.com/assets/24194621/20795822/8839f7bc-b816-11e6-9c3f-8821cd7316f8.PNG)

**Comment by jaw20** [comment]
Hmm... Try uninstalling Python 2.7.9 and delete any remaining folders and any files inside those folders in the python27 folder. Then try reinstalling python 2.7.9 making sure to also click on the option in the setup to add python.exe to path. Then install m3u8 only and then try running the script.

**Comment by Limitless99** [comment]
@jaw20 
I just did what you asked me to do. 
After running `pip freeze` it showed the following:

> iso8601==0.1.11
> m3u8==0.3.0

1. I have run the script again.
2. It installed the missing files automatically.
3. I entered 6 to download from queue and then this line showed up:  
![_4](https://cloud.githubusercontent.com/assets/24194621/20797582/be33cd90-b81e-11e6-8463-c94fb2a44cbd.PNG)
 
I thought it was a new problem but it actually started downloading 2 files:
![_4-2](https://cloud.githubusercontent.com/assets/24194621/20797644/122df344-b81f-11e6-9442-318f75ddec9d.PNG)

BUT... after finishing the download and merging, the file got deleted! I can't find it anywhere!
 
![_4-3](https://cloud.githubusercontent.com/assets/24194621/20797735/77f758aa-b81f-11e6-90a0-8c3f796857a9.PNG)

As you can see above, only the subtitles remain!

btw thanks for telling me about adding paython.exe option.

**Comment by jaw20** [comment]
Does it mention any error before it moves on to the next file?

**Comment by Limitless99** [comment]
Yes! it actually shows the same message as yours in #108

**Comment by jaw20** [comment]
There is a workaround for this, if you use one of the changes from #84 , I think it was https://github.com/einstein95/crunchy-xml-decoder/pull/84/commits/c73abafab82f3f6d41a7aba05edb41a0d4b1f03d . If you add that change in to your ultimate.py (using idle) you should be able to download files for the time being until hls is fixed.

**Comment by jaw20** [comment]
But if i were you I would close this issue and either post or subscribe to #108

**Comment by Limitless99** [comment]
@jaw20 
Yes as you mentioned, I can download RTMP files but not HLS!
I'll subscribe to your issue and see things from there.
Thank you for helping me this far
And thanks to @jsonn too!
