### ISSUE TITLE
unable to rip episode 3 to 5 of Is It Wrong to Try to Pick Up Girls in a Dungeon?

### ISSUE THREAD

**Issue by MidgardSerpent** [einstein95/crunchy-xml-decoder#11]
it looks as if the episode names are being phrased as commands, iv attached the output of episode 3. ![untitled](https://cloud.githubusercontent.com/assets/427573/7443407/f54486f0-f18a-11e4-9624-6ed85863b02b.png)

**Comment by einstein95** [comment]
Oh, it's tripping up on the | in the name. Because Windows.

**Comment by einstein95** [comment]
Fixed in cfce374
