### ISSUE TITLE
Not an issue but an idea: Automatically tag languages and add S00E00 to the file name.

### ISSUE THREAD

**Issue by ganon11000** [einstein95/crunchy-xml-decoder#13]
This would be useful for anyone using XMBC / Kodi:
After I download a video I have to put it through MKV merge and do the following:
edit the subtitle language code to be correct and mark it as a forced track
edit the audio language to Japanese
edit the file name to end with " - Crunchyroll_SXXEXX" so Kodi automatically adds it to my library.

It would be nice if you could edit it so the subtitle track is forced (--forced-track) and for the "_S00E00" tag to be added.

**Comment by einstein95** [comment]
Yeah, setting the subtitle language code and audio language code has been
on my "todo eventually if you actually remember to do this" list for a
while as it also is useful for playback via Plex. I'll definitely look into
this.

**Comment by ganon11000** [comment]
Also another feature that would be useful (and possibly easier to implement?) would be an option to automatically mark everything that gets downloaded as watched.

**Comment by alzamer2** [comment]
i can help you in this one if you like
send me message

**Comment by einstein95** [comment]
Added in #34
