### ISSUE TITLE
Append video quality to end of file name

### ISSUE THREAD

**Issue by sickness0666** [einstein95/crunchy-xml-decoder#14]
it would be good if it would auto append the video quality (360p, 480p, 720p, 1080p) to the end of the filename,
EG:
MY love  STORY!! Episode 7 - My Strength [720p]
or 
MY love  STORY!! Episode 7 - My Strength - 720p

**Comment by alzamer2** [comment]
hi einstein95
the video quality is the same as clip height (in pixel) which i add at my pull #34 (you already merged it)
please close this issue
