### ISSUE TITLE
Issue with _start.bat

### ISSUE THREAD

**Issue by MightyBirdy** [einstein95/crunchy-xml-decoder#15]
This is what happens when I try to run the script:

D:\Crunchyroll Downloader Toolkit DX>_start.bat "http://www.crunchyroll.com/gint
ama/gintama-season-2-253-265-gintama-classic-an-observation-journal-should-be-se
en-through-to-the-very-end-611943" > debug.log
Traceback (most recent call last):
  File "D:\Crunchyroll Downloader Toolkit DX\crunchy-xml-decoder\ultimate.py", l
ine 85, in <module>
    lang = altfuncs.config(0)
TypeError: config() takes no arguments (1 given)

What am I doing wrong?

**Comment by einstein95** [comment]
That was fixed in this commit https://github.com/einstein95/crunchy-xml-decoder/commit/b50229357b383f3eb24b425bb49306c79a9868ed

**Comment by MightyBirdy** [comment]
It's working now, thank you!
