### ISSUE TITLE
link issue

### ISSUE THREAD

**Issue by sickness0666** [einstein95/crunchy-xml-decoder#18]
http://www.crunchyroll.com/gintama/episode-269-forget-dates-remember-people-you-can-hide-your-porn-mags-but-you-cant-hide-your-678771

im guessing the issue is related to the *** in title name that cannot be used in windows file names

**Comment by einstein95** [comment]
Why does Gintama hate me ;_;
(will fix soon)

**Comment by sickness0666** [comment]
ahahaha, ya i know. i only had a couple issues, one was with the *** in a couple ep names, other was from EXTREMLY long names, which you had fixed. ive had issues sometimes with some other eps of shows with ' in the title when processing, instead of &quote;, but i just changed the ultimate.py to replace ' and &quote; with nothing

**Comment by sickness0666** [comment]
another issue link is:
http://www.crunchyroll.com/gintama/episode-11-look-overly-sticky-sweet-dumplings-are-not-real-dumplings-you-idiot-510056

issue is with the comma in the title name, stripping out the comma in ultimate.py fixes the issue

**Comment by einstein95** [comment]
Hmm... No issues with commas in titles. Could you give a URL whre you "had
issues sometimes with some other eps of shows with ' in the title when
processing, instead of "e;"?

**Comment by sickness0666** [comment]
i believe it was with a couple of episodes in hunter x hunter, they would error out when processing through the mkv merge i believe it was, i had ultimate.py just strip out the ' from the video title and had no issues since then

**Comment by sickness0666** [comment]
and that "e; was supposed to be the html code &quote, but i guess the comments auto changed it lol

**Comment by Zaphain** [comment]
http://www.crunchyroll.com/kill-la-kill/episode-1-if-only-i-had-thorns-like-a-thistle-644301
There's an issue with the ellipsis in the title

**Comment by einstein95** [comment]
Should be properly fixed now.
