### ISSUE TITLE
Problem with decode.py

### ISSUE THREAD

**Issue by Gonner** [einstein95/crunchy-xml-decoder#2]
Hello, i'm trying to download the french subtitle for a series, and here's what it appears to me.

--------------------------
---- Start New Export ----
--------------------------

CrunchyRoll Downloader Toolkit DX v0.98

This script downloads just the subtitles, for purposes nefarious or otherwise.

----------

Please Enter CrunchyRoll Video URL
http://www.crunchyroll.com/liar-game/episode-1-660811
Extracting subtitles from http://www.crunchyroll.com/liar-game/episode-1-660811
Traceback (most recent call last):
  File "D:\Users\Gonner\Downloads\crunchy-xml-decoder\crunchy-xml-decoder\decode
.py", line 19, in <module>
    from crunchyDec import CrunchyDec
  File "D:\Users\Gonner\Downloads\crunchy-xml-decoder\crunchy-xml-decoder\crunch
yDec.py", line 6, in <module>
    from Crypto.Cipher import AES
  File "D:\Users\Gonner\Downloads\crunchy-xml-decoder\crunchy-xml-decoder\Crypto
\Cipher\AES.py", line 50, in <module>
    from Crypto.Cipher import _AES
ImportError: cannot import name _AES

----------

****** Job completed successfully *****

Appuyez sur une touche pour continuer...

**Comment by darkmorpher** [comment]
```python
Booting up...
Traceback (most recent call last):
  File "C:\Crunchyroll Downloader Toolkit DX\crunchy-xml-decoder\ultimate.py", line 179, in <module>
    host_grr = re.search('fplive\.net', host) #why host_grr? well, there was a time when fplive videos couldn't be downloaded, so...
  File "C:\Program Files\Python27\lib\re.py", line 142, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or buffer
An error has occured. Please check "error.log" for the affected page url.
```

**Comment by Gonner** [comment]
I don't understand what you mean darkmorpher.

**Comment by alzamer2** [comment]
Gooner
for the problem "ImportError: cannot import name _AES"
this happen because the "Crypto" in the code is not complete use http://www.voidspace.org.uk/python/modules.shtml#pycrypto

and delete "Crypto" in crunchy-xml-decoder

**Comment by Gonner** [comment]
Oh thanks man ! I've delete Crypto et lxml, but one last probleme:
"The video's subtitles cannot be found, or are region-locked."

What must I do please ?

**Comment by Gonner** [comment]
Oh nothing, i've tried to do the same thing with the link original, it work, thanks !

**Comment by alzamer2** [comment]
Gooner
i want to ask you is the last code working with you?

**Comment by Gonner** [comment]
What do you mean by "the last code" ?
