### ISSUE TITLE
arabic subtitles give english subtitles in anime has arabic subtitles

### ISSUE THREAD

**Issue by mustafasalah** [einstein95/crunchy-xml-decoder#21]
hello,

first thanks for supporting Arabic Subtitles, But when I rip subtitles form anime has Arabic subtitle, it give me english Subtitles :(

And Thank You +1:

**Comment by einstein95** [comment]
What video are you trying to download, and can you try with the latest
revision?

**Comment by mustafasalah** [comment]
I tried this video : http://www.crunchyroll.com/my-love-story/episode-11-my-ocean-678437
And I Tried with lastet revision and result is same :(

**Comment by einstein95** [comment]
Okay, I've pushed one more revision, can you try it now? If it still
doesn't work, I'll add some stuff to see what's going wrong.

**Comment by mustafasalah** [comment]
when i rip video and subtitles (using _start.bat) i get Arabic subtitles (thank you veryyyyy much!!)
But if I rip Subtitle just from video (using _start_subs-only.bat) I get this message "the video subtitles cannot be found, or  are region-locked" .

And Thank you very Much Agin :)

**Comment by einstein95** [comment]
Ooh, I think I know what's going wrong. Will fix in a bit.

**Comment by einstein95** [comment]
Dunno why "a bit" was 10 days, but it's now been fixed in 1a6b3a82fee162bca2b65b2f80f1969c85b833df
