### ISSUE TITLE
Issue with downloading certain Language subtitle

### ISSUE THREAD

**Issue by GentoSan** [einstein95/crunchy-xml-decoder#22]
Hi einstein,
Thank you and to your friends whoever helped to make this great tool

I've a problem with the tool. When i use the first version which is the original one without any update, and use _start.bat it downloads the video in any other langauge but can't download the Arabic subtitle, seems not supported at that time. Now i downloaded your updated one but it's gotta worse, can't even download a video, it goes to the process stage then the cmd disappeared and nothing happen. 

What's the issue here?

**Comment by MidgardSerpent** [comment]
in the newer versions you need to install PyCrypto (http://www.voidspace.org.uk/python/modules.shtml#pycrypto) and lxml (https://pypi.python.org/pypi/lxml/3.2.5) for it to work

**Comment by GentoSan** [comment]
and so i've to install Python 3.4.2?

**Comment by einstein95** [comment]
No, download the python 2.x versions that match your installed version

**Comment by GentoSan** [comment]
Still the same...

**Comment by einstein95** [comment]
Try running start.bat from the command line and see if any errors appear.

**Comment by hunterxsasuke** [comment]
thank u einstein95 for this great tool, but i have the same problem  
whenever i try to download a video the cmd disappeared ?? 

is there any solution for this issue?

**Comment by hunterxsasuke** [comment]
i solved the problem 

thank u :)
