### ISSUE TITLE
Error downloading Death Note Drama episode 2

### ISSUE THREAD

**Issue by ganon11000** [einstein95/crunchy-xml-decoder#23]
The older version I have crashes at 1.7% and the latest version gives this error:
https://i.imgur.com/86yZvuP.png it seems to just mess up at the end (the MKV combining)

**Comment by einstein95** [comment]
Hopefully fixed with 4bcdd61d31187e198851196778b52a81e93b76bf and 08b71f977667763cc4daa50d85248fa30db64451
