### ISSUE TITLE
Unable to download HD versions from crunchyroll - it only downloads 360p quality now

### ISSUE THREAD

**Issue by denz013angel** [einstein95/crunchy-xml-decoder#24]
seems like crunchyroll changed something, every beginning of a show it seems to pull up the SD version first then starts playing in HD 1080p after. is there any way around this?

**Comment by einstein95** [comment]
All I can think of is check your cookies, try making them again.

**Comment by denz013angel** [comment]
deleted all cookies , tried a different computer as well. same thing goes. even tried different browsers. for some reason it only downloads the SD version instead of high definition . and i have a premium account too. it all happened 5 days ago.

**Comment by denz013angel** [comment]
found the problem. My account just went from free trial to full premium. then i just had to recreate the cookie on the bat file. Thanks so much einstein thats the only thing i didn't do.
lol.. much appreciated!

**Comment by alzamer2** [comment]
hi
it seem this issue has been resolved
i will closed it if there is no new replay after a week
