### ISSUE TITLE
Download problem in episode and subtitle file

### ISSUE THREAD

**Issue by mustafasalah** [einstein95/crunchy-xml-decoder#25]
Hello,

CrunchyRoll shortly before the trial to prevent viewing of the new episodes, which led to a not download part of the episode (preview) and subtitle file by the program to those who possess a normal membership .
Please help us in this problem by enabling download subtitle file again for people who have a a normal membership.

And thank you very much

**Comment by alzamer2** [comment]
first sorry for the delay in replay
i'm not sure i get it but can you try with new revision

**Comment by alzamer2** [comment]
as there is no replay
i will close this issue after 7 days from now

**Comment by mustafasalah** [comment]
I try new version and it works good.

Thanks ^_^
