### ISSUE TITLE
TypeError: ord() expected a character, but string of length 7 found

### ISSUE THREAD

**Issue by Gonner** [einstein95/crunchy-xml-decoder#26]
Hello, i've downloaded the lastest update (6 hour ago) from Github and got an error. I was trying to download the subtitle of this (http://www.crunchyroll.com/himouto-umaru-chan/episode-8-umaru-and-christmas-and-new-years-682815). I've <b>Python 2.7.9 (64 bits)</b>, <b>Python 2.7 lxml-3.3.5</b>, <b>Python 2.7 pycrypto-2.6</b>.

----------
CrunchyRoll Downloader Toolkit DX v0.98

This script downloads just the subtitles, for purposes nefarious or otherwise.

Please Enter CrunchyRoll Video URL
http://www.crunchyroll.com/himouto-umaru-chan/episode-8-umaru-and-christmas-and-new-years-682815
Extracting subtitles from http://www.crunchyroll.com/himouto-umaru-chan/episode-8-umaru-and-christmas-and-new-years-682815
Booting up...
D:\Users\Gonner\Downloads\crunchy-xml-decoder-master\crunchy-xml-decoder\decode.py:71: RuntimeWarning: Argument <type 'list'> is not an unicode object. Passing an encoded string will likely have unexpected results.
  sub_id = re.findall("id='([0-9]+)' .+? title='.+?" + re.escape(unidecode(lang)) + "'", xmllist)[0]
Traceback (most recent call last):
  File "D:\Users\Gonner\Downloads\crunchy-xml-decoder-master\crunchy-xml-decoder\decode.py", line 71, in <module>
    sub_id = re.findall("id='([0-9]+)' .+? title='.+?" + re.escape(unidecode(lang)) + "'", xmllist)[0]
  File "D:\Users\Gonner\Downloads\crunchy-xml-decoder-master\crunchy-xml-decoder\unidecode\__init__.py", line 37, in unidecode
    codepoint = ord(char)
TypeError: ord() expected a character, but string of length 7 found

****** Job completed successfully *****

Appuyez sur une touche pour continuer...

----------

Best regards.

**Comment by Gonner** [comment]
Thank you, now it says me "The video's subtitles cannot be found, or are region-locked". I tried the same link as before.

**Comment by einstein95** [comment]
Just added a new .bat file called "_error_test.bat". Please run it with the URL of the video you are having problems with and report back with the output.

**Comment by Gonner** [comment]
I didn't found the bat file called "_error_test.bat". But the problem appears only on the lastest videos. I think it's because i don't have premium account.

**Comment by einstein95** [comment]
If the video is premium only, probably yes.

**Comment by Gonner** [comment]
Ok, then thank you, i do not have problem anymore :)
