### ISSUE TITLE
crunchy-xml-decoder/decode.py error

### ISSUE THREAD

**Issue by adriannx** [einstein95/crunchy-xml-decoder#27]
Hello,

I try downloading a episode but i get this error:
![55989](https://cloud.githubusercontent.com/assets/5619504/9695478/cce56bee-5327-11e5-857e-e6cf1b0446f9.PNG)

**Comment by Gonner** [comment]
Download the lastest the laster version on the github:
![prtscr capture_2](https://cloud.githubusercontent.com/assets/10365716/9698813/7a617552-53c7-11e5-9446-047ce66400ca.png)

And you must have:
- Python 2.7.x
- PyCrypto 2.6 (http://www.voidspace.org.uk/python/modules.shtml#pycrypto)
- lxml 3.2.5 (https://pypi.python.org/pypi/lxml/3.2.5)

**Comment by adriannx** [comment]
Hello Gonner, thanks for reply.

I have installed all the requirements, but still gives me error. Don't know that I'm doing wrong. :(

Regards!

**Comment by Gonner** [comment]
The problem has changed. Did you correctly configure the file "settings.ini" ?

**Comment by adriannx** [comment]
Heelo Gonner,

Yes i have configure all and my premium account.

![capture1](https://cloud.githubusercontent.com/assets/5619504/9700253/c46ae652-53c1-11e5-881c-443991ced032.PNG)

**Comment by MidgardSerpent** [comment]
put a space between 720p and # (or start a new line)

**Comment by einstein95** [comment]
It looks like git converts all newlines to Unix format. Open it in a better
text editor, like Sublime Text or Notepad++. Notepad doesn't like the Unix
newlines and removes them when you save.

**Comment by adriannx** [comment]
Hello Guys,

Don't know, I'm doing wrong...
I have replace for this and nothing:
![998](https://cloud.githubusercontent.com/assets/5619504/9705217/31ae27c6-5483-11e5-8e4d-d44bf4c726a8.PNG)

Regards!

**Comment by Gonner** [comment]
Download Notepad++ and use it ._.

**Comment by alzamer2** [comment]
hi 
a new update was released
if the settings.ini has problem just delete it and run _start2.bat it will regenerate the default settings
PS:this issue will be closed after a week from now if there is no replay
