### ISSUE TITLE
proxy Tor doest work

### ISSUE THREAD

**Issue by adriannx** [einstein95/crunchy-xml-decoder#29]
Hello, i'm trying download from Cr using tor but doest work :(
the black windows closed automatic :(

Regards!
![001](https://cloud.githubusercontent.com/assets/5619504/9835266/f26816c4-59a7-11e5-88b5-208a9356618f.PNG)
![002](https://cloud.githubusercontent.com/assets/5619504/9835267/f27a3b9c-59a7-11e5-9709-8b7cac980b06.PNG)

**Comment by alzamer2** [comment]
as far i know this feature was disabled
download the latest version by "Download Zip"
