### ISSUE TITLE
_start.bat don´t merge .flv and .ass into .mkv

### ISSUE THREAD

**Issue by Deathmeduso** [einstein95/crunchy-xml-decoder#36]
First, sorry for my poor english.
I've just downloaded the new version and _start.bat doesnt merge video and audio into .mkv, the old version is working fine.
Help please.

**Comment by alzamer2** [comment]
can you put your windows name (32 or 64)
and picture of the command line

**Comment by Deathmeduso** [comment]
I'm using Windows 10 Pro x64. I can't post a picture because it doesnt send any error, simply when the download finishes it doesnt merge audio and video.

**Comment by alzamer2** [comment]
even if there is no error can you post the picture

**Comment by alzamer2** [comment]
hi can you go and download clone from
https://github.com/alzamer2/crunchy-xml-decoder/tree/subtitletag
it has debug function
just add debug after _start2.bat in the command prompt
