### ISSUE TITLE
Request about video xml's

### ISSUE THREAD

**Issue by Krak-ON** [einstein95/crunchy-xml-decoder#37]
I was wondering if it was possible to have a script that saves these types of xml's:

http://www.crunchyroll.com/xml/?req=RpcApiVideoPlayer_GetStandardConfig&media_id=682295&video_format=108&video_quality=80

Into the decoded version, for example:

http://pastebin.com/6wextcdH

**Comment by alzamer2** [comment]
it can but why do you need it

**Comment by Krak-ON** [comment]
I I just wanted to be able to save the xml to be able to view all the video parameters.
I have a premium account, so if I need that to login its fine.
I'm also running under OSX if that makes a difference.

**Comment by alzamer2** [comment]
ok done
check this fork
https://github.com/alzamer2/crunchy-xml-decoder/tree/subtitletag
 just add debug after _start2.bat in the command prompt
it will dump debug.c.log, debug.p.log and decoded_xml.txt

**Comment by Krak-ON** [comment]
I can't run .bat files since im on OSX.

**Comment by Krak-ON** [comment]
I ran the debug.py and got this:
<pre><code>Booting up...
Please enter Crunchyroll video URL:
http://www.crunchyroll.com/non-non-biyori/episode-1-i-became-a-first-grader-682295
/bin/sh: title: command not found
Traceback (most recent call last):
  File "debug.py", line 72, in <module>
    import ultimate
  File "/Users/Ruben/Downloads/crunchy-xml-decoder-subtitletag/crunchy-xml-decoder/ultimate.py", line 82, in <module>
    lang1, lang2, forcesub = altfuncs.config()
  File "/Users/Ruben/Downloads/crunchy-xml-decoder-subtitletag/crunchy-xml-decoder/altfuncs.py", line 18, in config
    quality = configr.get('SETTINGS', 'video_quality')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'SETTINGS'</code></pre>

**Comment by alzamer2** [comment]
I don't know about OSX
but don't you have some thing like windows commandline
if you have run it from the code directory, like this:
<directory of crunchy-xml-decoder(here is settings.ini)>\crunchy-xml-decoder\debug.by
or you can copy settings.ini and put at the side of debug.by

**Comment by alzamer2** [comment]
Krak-ON
if everything has worked out please replay so we can know

**Comment by Krak-ON** [comment]
It worked, thank you so much.
