### ISSUE TITLE
Bug in code

### ISSUE THREAD

**Issue by kitamuramms** [einstein95/crunchy-xml-decoder#38]
Hello, Just passing by ta alert fora a bug in your code. 

File: altfuncs.py

line 31 #     forcesub = configr.getboolean('SETTINGS', 'forcesubtitle')
ling 32 #     forcesub = configr.getboolean('SETTINGS', 'forceusa')

In the line 32 it should be "forceusa = configr.getboolean('SETTINGS', 'forceusa')"

Also "forceusa " should be set as a global var. Anyway after all the corrections, it couldn't connect to the website. It's a shame, but hope you improve it.

Keep up the good work!

**Comment by einstein95** [comment]
Fixed
