### ISSUE TITLE
Another region restriction problem?

### ISSUE THREAD

**Issue by TheTroubledErick** [einstein95/crunchy-xml-decoder#40]
As you can see from this screen, I'm not able to download the subtitles from the series "Himouto! Umaru-chan".
![issue](https://cloud.githubusercontent.com/assets/14983744/10291275/403a4418-6ba9-11e5-80ca-12495286f17b.jpg)

Both "Himouto! Umaru-chan" and "MY love STORY!!", are available for free in my country (Italy).
I have an account but it's not a premium one, I don't think that's the problem tho, I've always been able to download subtitles making cookies from it with your program.

Here you can find my debug.html:
https://mega.nz/#!tg0w2RQL!4Q02MTzo2dJ79kUJI74-QNUqiWjQKg5DaHutnOJ3enc

The only difference I can notice is that most (if not all) of the subtitles I downloaded in the past (like "My love STORY!!") came from series with many languages available, where this Umaru-chan only shows the italian sub (even if the english one clearly exist 'cause I found it here http://9xbuddy.com/download?url=http%3A%2F%2Fwww.crunchyroll.com%2Fhimouto-umaru-chan%2Fepisode-1-umaru-and-onii-chan-682801)

I'm not too skilled in this area but I'll try to be as helpful as possible to try making you fix this issue. o7

p.s. Thank you very much for your amazing work :)

**Comment by alzamer2** [comment]
hello
thank for the post
a new option in settings.ini has been added
forceusa
this option turn on internal option please try it out and see what happen

**Comment by TheTroubledErick** [comment]
It seems it let me download successfully the english version of the subtitles, which was previously not possible tho, but I need the Italian ones :/

**Comment by TheTroubledErick** [comment]
While waiting for your help I noticed that a new "repacked" version of the program is out.
After trying it, it was not possible to type in any character when you're required to insert the password.
Same problem with both .py and .bat.

**Comment by alzamer2** [comment]
yes the password are typing but hidden

**Comment by TheTroubledErick** [comment]
I see.
From a user point of view, in my opinion, it's not really intuitive, and now you can't even use the right click to paste anything (without using the dos QuickEdit Mode).
Anyway my problem persist, but this time with this version the Umaru series tells me that I have not a premium account and the program stops working.
While testing on old series give me the same message, but it's followed, right after, by the creation of all the .ass files. 
Isn't it possible to do something similar to "forceusa" for my country? To use a forced italian session ID or something? Because I have free access to that streaming using my browser, so the files are there. Is it possibile that the program is acting like I'm not from Italy?
I'm sorry if I'm saying something stupid but keep in mind my knowledge about those things is quite scarce ^^"

**Comment by alzamer2** [comment]
Ok 
1st. You can right click title bar>edit>past or run crunchy-xml-decoder.bat
2nd. Are you free user? If not then there is problem with input or the code foe cookies generation
3rd. Forceusa is more and less proxy method, so what the point to make it look like you live in italy if you who live in italy cant play the video?

As i said this series is weird normaly if you play ani video at crunchy if you right click the video a list with all subtitle show, but this series only show arabic for me and with proxy english only, i did not check other languge but maybe you cant play at any of erupian countries

**Comment by TheTroubledErick** [comment]
1. Oops. (ಠ▃ಠ)"
2. I'm a free user.
3. I, who live in Italy, CAN play the video, using my browser I can both access to video and italian subtitles.
![immagine](https://cloud.githubusercontent.com/assets/14983744/10364678/c5861fdc-6dbd-11e5-8c45-7eb647178d8c.jpg)

This is why I thought of forcing the italian ID, maybe the program, for some odd reason, behave like I'm not from Italy  乁[◕˵ - ˵◕]ㄏ

**Comment by alzamer2** [comment]
will this is bad that mean that crunchy working working on new codei will check something

**Comment by alzamer2** [comment]
i want to check something
[altfuncs.txt](https://github.com/einstein95/crunchy-xml-decoder/files/10012/altfuncs.txt)
rename this file from altfuncs.txt to altfuncs.py and replace the one in crunchy-xml-decoder (the one with ultimate.py
and try it out with out proxy

**Comment by TheTroubledErick** [comment]
Result:
![immagine](https://cloud.githubusercontent.com/assets/14983744/10368038/ac20c5fe-6dd3-11e5-96c4-849b2c0561bd.jpg)

**Comment by alzamer2** [comment]
ok i tried to add location to the cookies file try this one
[altfuncs.txt](https://github.com/einstein95/crunchy-xml-decoder/files/10878/altfuncs.txt)
rename this file from altfuncs.txt to altfuncs.py and replace the one in crunchy-xml-decoder (the one with ultimate.py
 and try it out with out proxy

**Comment by TheTroubledErick** [comment]
Σ(ノ°▽°)ノ It worked!1!!1!!
✧*.◟(ˊᗨˋ)◞.*✧
＼（　　⌒　∇　⌒　　）／

Thank you very much!

**Comment by alzamer2** [comment]
that good and all
but we need to fix the problem

**Comment by TheTroubledErick** [comment]
Tell me what can I do to help you.

**Comment by TheTroubledErick** [comment]
As far as I understood you changed the c_locale to ita when not forceusa, so basically my previously generated cookies where wrong about my default language. Was something like this?
If so couldn't you implement a similar change for any language forcing the cookies to utilize the the OS language? Not sure if possibile and anyway I would be a workaround, but probably is easy to do.

**Comment by alzamer2** [comment]
yes and no
the login function in the code don't save c_locale in cookies (it's for location)
and the "Himouto! Umaru-chan" show page need that value, it only show the subtitle of your language and the default is us and you live in Italy (for example in page of the show if you change the localization for English (us) it will show that you cant play the video)

**Comment by adriannx** [comment]
Hello bro, how you download by proxy? i cant download series only avalible from europe

**Comment by TheTroubledErick** [comment]
But you forced that value letting me download my language subtitles, no? 
Even if the login function can't handle that.
So you just need to know what language the user need (not what the cookies think the default is) and make the program "force" that language into the cookies. Wouldn't be enough?

**Comment by alzamer2** [comment]
sorry adriannx i cant understand you
TheTroubledErick, i want you to try this
in the download crunchy-xml-decoder (with original the altfuncs.py) try to add ?locale=itIT to the link
like this:http://www.crunchyroll.com/himouto-umaru-chan/episode-1-umaru-and-onii-chan-682801?locale=itIT
and try to download(there is no need to continue just start it and see if it begin to download or not)

**Comment by TheTroubledErick** [comment]
Tried on the version without the modified .py you gave me and it says downloaded, but the export folder is empy.
![immagine](https://cloud.githubusercontent.com/assets/14983744/10408442/e0535866-6efd-11e5-83c1-fb5e24074e3d.jpg)

**Comment by alzamer2** [comment]
hmm, ok then this method is not working
i will try make it work with desired subtitle language

**Comment by alzamer2** [comment]
ok check out repository i update the code try it out
don't forget to enable the cookie localize option in setting (you need to exit and run again he code to reload the settings)

**Comment by TheTroubledErick** [comment]
It worked.
