### ISSUE TITLE
Can't download from another territory.

### ISSUE THREAD

**Issue by adriannx** [einstein95/crunchy-xml-decoder#41]
Hello,
I have a problem when trying to download other territory, i'm from france and wanna download God eater, this serie not available for my country.

When try download a video
![95](https://cloud.githubusercontent.com/assets/5619504/10407440/4bbd6d24-6eb0-11e5-9218-05cc0dfed904.png)

Regards!

**Comment by adriannx** [comment]
Here the file debug.html

https://mega.nz/#!rgQQDTCY!9MeRKhly28vpa1r7dftd7OqmMoFZUkO7SweMXfxTSxU

Regards!

**Comment by alzamer2** [comment]
ok, first of all in the setting.ini change 
forceusa = false
to
forceusa = true

2nd there is only 3 subtitle for this show (English, Portugues, and Espanol)
if there is not anything else please close the issue

**Comment by adriannx** [comment]
Hello,
No support Espanol_Espana?

Regards!

**Comment by alzamer2** [comment]
I checked it with us proxy only those subtitle show up

**Comment by adriannx** [comment]
Hello Alzamer2,

Thank you! :)

**Comment by adriannx** [comment]
Hello, i'm try download this video: http://www.crunchyroll.com/divine-gate/episode-1-endless-rain-692995  from España, but got error.

I have configure:

forceusa = true
![9512](https://cloud.githubusercontent.com/assets/5619504/12272030/1d0eba98-b92c-11e5-8712-a976e8f83933.JPG)

Regards!
