### ISSUE TITLE
new way to put quality in final name

### ISSUE THREAD

**Issue by alzamer2** [einstein95/crunchy-xml-decoder#42]
hi einstein95
i tried new way to put quality in final name but i only have free account can you try it for me for 1080p
you can use the 2min show as test
http://www.crunchyroll.com/himegoto/episode-1-i-feel-like-ive-lost-as-a-girl-658435

**Comment by MidgardSerpent** [comment]
i can send you a 48hr pass if you want

**Comment by alzamer2** [comment]
hoo, that interesting
can you send it to me,please?
later on can you tell me  how to get it even if it for 1hr pass that ok with me

**Comment by MidgardSerpent** [comment]
github doesn't have a pm function so you will have to take it as soon as i post it

**Comment by alzamer2** [comment]
ok

**Comment by MidgardSerpent** [comment]
https://www.crunchyroll.com/acct/?action=guestpass&code=M7BETRM78U6

**Comment by alzamer2** [comment]
taken it

**Comment by alzamer2** [comment]
he say its not correct,maybe some one use it already
T.T

**Comment by MidgardSerpent** [comment]
the code says its still valid, post the code in here http://www.crunchyroll.com/guest_pass

**Comment by alzamer2** [comment]
thanks it worked i will try it out

**Comment by alzamer2** [comment]
yes it worked
thanks MidgardSerpent
