### ISSUE TITLE
new function in login

### ISSUE THREAD

**Issue by alzamer2** [einstein95/crunchy-xml-decoder#44]
hi can any Premium Member help, i want to put new function in login to show if the user normal member or Premium, all you have to do is open this link(it show the status of account)
https://www.crunchyroll.com/acct/membership/?locale=enUS
then save the page as html and upload it here
thanks

ps:dont worry if you even if you save it in html the password will not show

**Comment by einstein95** [comment]
[Crunchyroll - Account Management.txt](https://github.com/einstein95/crunchy-xml-decoder/files/15731/Crunchyroll.-.Account.Management.txt)

**Comment by alzamer2** [comment]
ok i update the code and we need to test it
it should say when you login "Login as Guest/Free Member/Premium Member/Premium+ Member"
and when you run the code it will show the user name and Membership type

>note:i tested Guest and Free Member

**Comment by ganon11000** [comment]
Can confirm it is working:
http://i.imgur.com/ETWhiWY.png

Have to say this is the best update ever! The fact it halts and then end instead of shuts is great to see if it worked or not while left unattended, the fact it tells you what is installed / missing etc.. is all amazing!
