### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by blalsad** [einstein95/crunchy-xml-decoder#45]
Hey

When i add the url video, i have this error : 

![cr](https://cloud.githubusercontent.com/assets/3245665/10621421/47f20c5e-7770-11e5-87f5-74ee56694c34.jpg)

What's the problem ? 

Thnak's in advance

**Comment by alzamer2** [comment]
That weired
The error say that you are not login(no cookies file)
But it should test that you are login at start of the of the script and try option login

**Comment by alzamer2** [comment]
Ok try to add new file (new text file) and see what happened,ic you were asked about administrator right then this is the problem(just unpack the script in defrent location).

**Comment by alzamer2** [comment]
thanks for comment
after i checked the code, it seem that i forget a critical line i have already added it
download the script again and try it out

**Comment by blalsad** [comment]
It works :)

Many Thanks :)

**Comment by alzamer2** [comment]
no problem

**Comment by alzamer2** [comment]
no problem

**Comment by Flwk** [comment]
I have an another error, can you go to the last issu ?

Many thanks in advance
