### ISSUE TITLE
CAN'T DOWNLOAD

### ISSUE THREAD

**Issue by Flwk** [einstein95/crunchy-xml-decoder#47]
Hey

I have a new probleme

When i want to download an episode, the script told me that i have to create an issue in Github and send the debug.html file

This is the debug.html file : http://www31.zippyshare.com/v/wt6N0kb6/file.html

Many Thanks in advance :)

**Comment by deforation** [comment]
Hello

I faced the same problem.
Until the fix is applied to the master, you can try it with this one.

This worked for me:
https://github.com/einstein95/crunchy-xml-decoder/issues/46
