### ISSUE TITLE
Possible to use this on linux debian ?

### ISSUE THREAD

**Issue by Gonner** [einstein95/crunchy-xml-decoder#51]
It works fine in windows, but is it possible to use this on linux (debian) ? I've python 2.7.9, lxml and pycrypto, and i got this error:

Traceback (most recent call last):
  File "crunchy-xml-decoder.py", line 9, in <module>
    import functtest
  File "crunchy-xml-decoder/functtest.py", line 23, in <module>
    python_bit_=re.findall("[0-9][0-9] bit",sys.version).pop()
IndexError: pop from empty list

**Comment by alzamer2** [comment]
Ok i'm windows user and i did not test it at unix
And you are the first unix user who said this problem

Can test someting for me
Go to python dir
Run it consle
Type 2 line >>

Import sys
Sys.version

And then tell me what you get at output

**Comment by alzamer2** [comment]
lol i dont know how i closed
any way i edit the code so can you test iy out and see what happen

**Comment by Gonner** [comment]
Hello, thank you to help me. Now i got this:

python version=4.9.2 64 bit
OS Version=Linux 3.16.0 4 amd64 x86_64 with debian 8.2
Traceback (most recent call last):
  File "crunchy-xml-decoder.py", line 9, in <module>
    import functtest
  File "crunchy-xml-decoder/functtest.py", line 35, in <module>
    print "System Type="+os.environ['PROCESSOR_ARCHITECTURE']
  File "/usr/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'PROCESSOR_ARCHITECTURE'

**Comment by alzamer2** [comment]
ok this info is for debug and you can skip this line by adding # before the line (35)
but can you help me to fix it so that it does not repeat
can you post the output of this line here

import os;os.environ

**Comment by alzamer2** [comment]
ok i did some research in internet and it seem linux dose mot have value PROCESSOR_ARCHITECTURE in its environment variables
can you test the code now and tell me what you get

**Comment by Gonner** [comment]
Sorry, dunno how to do import os:os.environ

With the new code:

python version=4.9.2 64 bit
OS Version=Linux 3.16.0 4 amd64 x86_64 with debian 8.2
System Type=x86_64
Can't find the Binary Folder
Crypto installed
lxml installed
Do you have an account [Y/N]?y
Username: Gonner-
Password(don't worry the password are typing but hidden:
Login as Free Member successfully.
Options:
0.- Exit
1.- Download Anime 
2.- Download Subtitle only
3.- Login
4.- Login As Guest
5.- Run Queue
6.- Settings

> 2
Please enter Crunchyroll video URL:
http://www.crunchyroll.com/the-perfect-insider/episode-6-crimson-resolve-686455

--------------------------
---- Start New Export ----
--------------------------

CrunchyRoll Downloader Toolkit DX v0.98

Crunchyroll hasn't changed anything.

If you don't have a premium account, go and sign up for one now. It's well worthit, and supports the animators.

----------
Booting up...

Traceback (most recent call last):
  File "crunchy-xml-decoder.py", line 354, in <module>
    makechoise()
  File "crunchy-xml-decoder.py", line 292, in makechoise
    decode.decode(raw_input('Please enter Crunchyroll video URL:\n'))
  File "crunchy-xml-decoder/decode.py", line 42, in decode
    lang1, lang2, forcesub, forceusa, localizecookies, vquality, onlymainsub = altfuncs.config()
  File "crunchy-xml-decoder/altfuncs.py", line 18, in config
    quality = configr.get('SETTINGS', 'video_quality')
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'SETTINGS'

**Comment by Gonner** [comment]
hope there is not confidentialy code:

Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ
{'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'XDG_CURRENT_DESKTOP': 'GNOME', 'LOGNAME': 'kd', 'USER': 'kd', 'HOME': '/home/kd', 'XDG_VTNR': '7', 'PATH': '/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games', 'WINDOWPATH': '7', 'SSH_AGENT_PID': '1282', 'LANG': 'fr_FR.utf8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'XAUTHORITY': '/var/run/gdm3/auth-for-kd-mHcRYv/database', 'SESSION_MANAGER': 'local/R2D2-debian-main:@/tmp/.ICE-unix/1245,unix/R2D2-debian-main:/tmp/.ICE-unix/1245', 'SHLVL': '1', 'DISPLAY': ':0', 'WINDOWID': '50331654', 'DESKTOP_AUTOSTART_ID': '10a34ba97bc6ad4f10144818189536476600000012450001', 'GPG_AGENT_INFO': '/run/user/1000/keyring/gpg:0:1', 'USERNAME': 'kd', 'XDG_SESSION_DESKTOP': 'default', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'VTE_VERSION': '3801', 'GDMSESSION': 'default', 'XDG_SESSION_ID': '1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-9ADi0DnDxi,guid=8255c0ea0db4fb138a1863d656518087', '_': '/usr/bin/python', 'DESKTOP_SESSION': 'default', 'OLDPWD': '/home/kd', 'GDM_LANG': 'fr_FR.utf8', 'XDG_DATA_DIRS': '/usr/share/gnome:/usr/local/share/:/usr/share/', 'PWD': '/home/kd/T\xc3\xa9l\xc3\xa9chargements', 'XDG_MENU_PREFIX': 'gnome-', 'LS_COLORS': 'no=00:fi=00:di=34:ow=34;40:ln=35:pi=30;44:so=35;44:do=35;44:bd=33;44:cd=37;44:or=05;37;41:mi=05;37;41:ex=01;31:*.cmd=01;31:*.exe=01;31:*.com=01;31:*.bat=01;31:*.reg=01;31:*.app=01;31:*.txt=32:*.org=32:*.md=32:*.mkd=32:*.h=32:*.c=32:*.C=32:*.cc=32:*.cpp=32:*.cxx=32:*.objc=32:*.cl=32:*.sh=32:*.bash=32:*.csh=32:*.zsh=32:*.el=32:*.vim=32:*.java=32:*.pl=32:*.pm=32:*.py=32:*.rb=32:*.hs=32:*.php=32:*.htm=32:*.html=32:*.shtml=32:*.erb=32:*.haml=32:*.xml=32:*.rdf=32:*.css=32:*.sass=32:*.scss=32:*.less=32:*.js=32:*.coffee=32:*.man=32:*.0=32:*.1=32:*.2=32:*.3=32:*.4=32:*.5=32:*.6=32:*.7=32:*.8=32:*.9=32:*.l=32:*.n=32:*.p=32:*.pod=32:*.tex=32:*.go=32:*.sql=32:*.bmp=33:*.cgm=33:*.dl=33:*.dvi=33:*.emf=33:*.eps=33:*.gif=33:*.jpeg=33:*.jpg=33:*.JPG=33:*.mng=33:*.pbm=33:*.pcx=33:*.pdf=33:*.pgm=33:*.png=33:*.PNG=33:*.ppm=33:*.pps=33:*.ppsx=33:*.ps=33:*.svg=33:*.svgz=33:*.tga=33:*.tif=33:*.tiff=33:*.xbm=33:*.xcf=33:*.xpm=33:*.xwd=33:*.xwd=33:*.yuv=33:*.aac=33:*.au=33:*.flac=33:*.m4a=33:*.mid=33:*.midi=33:*.mka=33:*.mp3=33:*.mpa=33:*.mpeg=33:*.mpg=33:*.ogg=33:*.ra=33:*.wav=33:*.anx=33:*.asf=33:*.avi=33:*.axv=33:*.flc=33:*.fli=33:*.flv=33:*.gl=33:*.m2v=33:*.m4v=33:*.mkv=33:*.mov=33:*.MOV=33:*.mp4=33:*.mp4v=33:*.mpeg=33:*.mpg=33:*.nuv=33:*.ogm=33:*.ogv=33:*.ogx=33:*.qt=33:*.rm=33:*.rmvb=33:*.swf=33:*.vob=33:*.webm=33:*.wmv=33:*.doc=31:*.docx=31:*.rtf=31:*.odt=31:*.dot=31:*.dotx=31:*.ott=31:*.xls=31:*.xlsx=31:*.ods=31:*.ots=31:*.ppt=31:*.pptx=31:*.odp=31:*.otp=31:*.fla=31:*.psd=31:*.7z=1;35:*.apk=1;35:*.arj=1;35:*.bin=1;35:*.bz=1;35:*.bz2=1;35:*.cab=1;35:*.deb=1;35:*.dmg=1;35:*.gem=1;35:*.gz=1;35:*.iso=1;35:*.jar=1;35:*.msi=1;35:*.rar=1;35:*.rpm=1;35:*.tar=1;35:*.tbz=1;35:*.tbz2=1;35:*.tgz=1;35:*.tx=1;35:*.war=1;35:*.xpi=1;35:*.xz=1;35:*.z=1;35:*.Z=1;35:*.zip=1;35:*.ANSI-30-black=30:*.ANSI-01;30-brblack=01;30:*.ANSI-31-red=31:*.ANSI-01;31-brred=01;31:*.ANSI-32-green=32:*.ANSI-01;32-brgreen=01;32:*.ANSI-33-yellow=33:*.ANSI-01;33-bryellow=01;33:*.ANSI-34-blue=34:*.ANSI-01;34-brblue=01;34:*.ANSI-35-magenta=35:*.ANSI-01;35-brmagenta=01;35:*.ANSI-36-cyan=36:*.ANSI-01;36-brcyan=01;36:*.ANSI-37-white=37:*.ANSI-01;37-brwhite=01;37:*.log=01;32:*~=01;32:*#=01;32:*.bak=01;33:*.BAK=01;33:*.old=01;33:*.OLD=01;33:*.org_archive=01;33:*.off=01;33:*.OFF=01;33:*.dist=01;33:*.DIST=01;33:*.orig=01;33:*.ORIG=01;33:*.swp=01;33:*.swo=01;33:*,v=01;33:*.gpg=34:*.gpg=34:*.pgp=34:*.asc=34:*.3des=34:*.aes=34:*.enc=34:*.sqlite=34:', 'XDG_SEAT': 'seat0'}
>>>

**Comment by alzamer2** [comment]
three points
1-did you change any thing in video-engine?
like change the name of rtmpdump.exe to rtmpdump or download linux version of it
2- can you see settings.ini in the code directory?
2-are you sure you want to continue?
this code was written as windows base but because we use Python we can make it support linux directly but if you are willing to help i can try that but as i said i dont have linux so all the testing will be on you

**Comment by Gonner** [comment]
I change anything, i've install linux a 2 weeks ago. I just found another program who works on linux. Thank you for trying to help me!

**Comment by alzamer2** [comment]
no problem at all
