### ISSUE TITLE
Queue just for subtitles

### ISSUE THREAD

**Issue by SkyAFS** [einstein95/crunchy-xml-decoder#54]
I am new in github,  i dont know were to ask, but i have a problem, maybe someone can help me, i have several japanese blurays but they dont have subs, and i want to download the subs from crunchy and put on my rips, just for myself,  the problem is that is more than 300 episodes, is there any way to make queue just for subs on english???

sorry if i make something wrong, or if my english is not right

**Comment by alzamer2** [comment]
hi
to tell you the truth to add this function in the code will take some time
but the cide was constructed so it can take outside function like any cmd program
so if you used this batch file(just rename it from sub-queue.txt to sub-queue.bat and add it to the code folder right beside crunchy-xml-decoder.py)
[sub-queue.txt](https://github.com/einstein95/crunchy-xml-decoder/files/49564/sub-queue.txt)
i think it can give you what you want

PS:if every thing was tested and ok close this issue

**Comment by SkyAFS** [comment]
this is amazing, thanks
