### ISSUE TITLE
Had an issue, tried to reinstall it

### ISSUE THREAD

**Issue by albireon** [einstein95/crunchy-xml-decoder#58]
EDIT: I got it working somehow! Now it says it failed to login, but it worked before I reinstalled it. (Just logging in though)
I have upper case letters and numbers in my password. (EDIT: changed password, still didn't work)
I tried changing localizesettings to true.
I want the german subs btw. , everything else seems to work.
I'm thankfull for any help!

xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

Now I get this error:

![3unbenannt](https://cloud.githubusercontent.com/assets/16622029/12215619/516fa8ce-b6c5-11e5-86ed-50b3857afc2d.png)

Sorry, I have no experience with any code D:
It worked, then it said there is an issue with connecting to crunchyroll or something like that.

I have a premium account and everything.
But now I can't even install it correctly, help please!

And btw: It says I have Python 2.7.1 but I have 2.7.5 :s

**Comment by webtax** [comment]
i had login failed issue, eventually i copied the cookie data directly into the cookie file and that worked for now , can download succesfully
