### ISSUE TITLE
Error Help

### ISSUE THREAD

**Issue by madalbino1** [einstein95/crunchy-xml-decoder#60]
looking for help with this error
![error](https://cloud.githubusercontent.com/assets/16675736/12280623/0c5e1b34-b955-11e5-81e6-4d963e282392.png)

**Comment by Kamekameha** [comment]
This happens because Crunchyroll has more options, `video_encode_quality`, in their API than this dictionary provides. Usually when the content needs a Premium account depending on the type of the content (anime or drama).

**Comment by madalbino1** [comment]
thanks grabbed your fix and it works with no more issues on the videos I was error out on before
