### ISSUE TITLE
Login failed message

### ISSUE THREAD

**Issue by Jfigs101** [einstein95/crunchy-xml-decoder#69]
I have a trial account until August 9. I tried to log in as a premium user and receive the 'Login failed' message. Any fixes for this or is the problem with the trial account?

Thank You

**Comment by rcyclope** [comment]
no pb for me the login work fine 
have you try this : 
site = session.get('https://www.crunchyroll.com/acct/membership/', headers=headers, verify=True).text
You need to change it to
site = session.get('https://www.crunchyroll.com/acct/membership', headers=headers, verify=True).text

line 20 in login.py

**Comment by iCertys** [comment]
@rcyclope
Problem was answert in #63 

It was to add:
elif re.search(re.escape(' ga(\'set\', \'dimension5\', \'freetrail\');'), site):
status = 'Premium Member'

after line 29.
